[[plugins]]
  package = "netlify-plugin-minify-html"
  # Specify which deploy contexts we'll minify HTML in.
  # Supports any Deploy Contexts available in Netlify.
  # https://docs.netlify.com/site-deploys/overview/#deploy-contexts
  [plugins.inputs]
    contexts = [
      'production',
      'branch-deploy',
      'deploy-preview'
    ]
  [plugins.inputs.minifierOptions]
    removeComments = false
    collapseInlineTagWhitespace = false